# DiTango Configuration

# Basic parameters
model-name: stepvideo
ditango-base: ./ditango/
output-fn: ./Tango_evaluate/tango
tag: test

# Generation parameters
seed: 42
num-layers: 48
num-inference-steps: 50

# Performance testing parameters
enable-timing: true
do-preprocess: false

# Distributed parameters
do-cfg-parallel: false

# Baseline experiment parameters
use-ditango: true
use-ulysses: false
use-distrifusion: false
use-pab: false

# RedundancyMap configuration
stride-dividers: [8, 4, 2, 1]  # Divider values from largest stride to smallest
stride-percentiles: [0, 0, 90]  # Percentile thresholds for redundancy mapping