# DiTango Configuration

# Basic parameters
model-name: cogvideox-5b
ditango-base: ./ditango/
output-fn: ./result/
tag: redun

# Generation parameters
seed: 42
num-layers: 42
num-inference-steps: 50

# Performance testing parameters
enable-timing: true
do-preprocess: false

# Distributed parameters
do-cfg-parallel: true

# Baseline experiment parameters
use-ringfusion: true
use-ulysses: false
use-distrifusion: false
use-easy-cache: false

# RedundancyMap configuration
stride-dividers: [8, 4, 2, 1]  # Divider values from largest stride to smallest
stride-percentiles: [0, 40, 90]  # Percentile thresholds for redundancy mapping