# DiTango Configuration

# Basic parameters
model-name: cogvideox-5b
ditango-base: ./ditango/
output-fn: ./Tango_evaluate/df
tag: test

# Generation parameters
seed: 42
num-layers: 42
num-inference-steps: 50

# Performance testing parameters
warmup: 0
repeat: 2
enable-timing: false

# Distributed parameters
gpus: null
node: null
do-cfg-parallel: false

# Baseline experiment parameters
use-ringfusion: false
use-ulysses: false
use-distrifusion: true
use-easy-cache: false

# StrideMap configuration
stride-dividers: [8, 4, 2, 1]  # Divider values from largest stride to smallest
stride-percentiles: [0, 40, 90]  # Percentile thresholds for redundancy mapping